### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sbortman** [donovanmuller/spring-cloud-dataflow-server-openshift#14]
Hello,

I was hoping to take this for a test drive but ran into trouble quick.   :-(
Any help would be great.   Thanks!

--scottie

`[ERROR] Failed to execute goal on project spring-cloud-dataflow-server-openshift-autoconfig: Could not resolve dependencies for project org.springframework.cloud:spring-cloud-dataflow-server-openshift-autoconfig:jar:1.1.0.RELEASE: Failed to collect dependencies at org.springframework.cloud:spring-cloud-deployer-openshift:jar:1.1.0.RELEASE: Failed to read artifact descriptor for org.springframework.cloud:spring-cloud-deployer-openshift:jar:1.1.0.RELEASE: Could not transfer artifact org.springframework.cloud:spring-cloud-deployer-openshift:pom:1.1.0.RELEASE from/to spring-snapshots (http://repo.spring.io/libs-snapshot-local): Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/springframework/cloud/spring-cloud-deployer-openshift/1.1.0.RELEASE/spring-cloud-deployer-openshift-1.1.0.RELEASE.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]
[ERROR]`

**Comment by donovanmuller** [comment]
Thanks for trying the OpenShift deployer server out @sbortman!

When building this project I always have done a local `mvn install` of [spring-cloud-deployer-openshift](https://github.com/donovanmuller/spring-cloud-deployer-openshift), so have not experienced this before myself.

The `spring-cloud-deployer-openshift-1.1.0.RELEASE` artifact is deployed to [this Bintray repository](https://bintray.com/donovanmuller/switchbit-public/spring-cloud-deployer-openshift).
However, the default `spring` maven profile does not include the repository settings to resolve it. As a workaround, you can create a `.settings.xml` file in the root of this project locally, with the following contents:

```xml
```

**Comment by sbortman** [comment]
Donovan,  

Thank for the speedy reply.     I followed the "build your own deplolyer" advice and used v1.1.0.RELEASE git tags for both projects.  That gets me to the next set of hurdles.   That's the good news, the bad news is that you've probably not heard the last from me.  ;-)

(Following along your guide)

--scottie

**Comment by donovanmuller** [comment]
👍 Looking forward to helping!

**Comment by donovanmuller** [comment]
@sbortman Can this issue be closed?

**Comment by sbortman** [comment]
Hey Donovan,

Yes,  I think you can close it,   I thought I mentioned that a while back
but
maybe I didn't.

While I have your attention,  I was just wondering if/when the OpenShift
flavor of SCDF will be upgraded to match the Kubernetes version 1.2.2.

Could that be in the works?  :-)

Thanks!
--scottie

**Comment by donovanmuller** [comment]
The 1.2.0 release includes Data Flow 1.2.2: https://github.com/donovanmuller/spring-cloud-dataflow-server-openshift/releases/tag/v1.2.0.RELEASE
