### ISSUE TITLE
Downloadable jar

### ISSUE THREAD

**Issue by jakudaba** [donovanmuller/spring-cloud-dataflow-server-openshift#15]
Hi Donovan

Thank you for adopting the dataflow server to openshift.  We would like to have an URL in our dockerimage to directly download the jar and embedd it in our docker image. Would it be possible to make a release of the jar directly asside the zip?

Best regards

Manu

**Comment by donovanmuller** [comment]
Pleasure 😄 

You can get a downloadable Jar here (from the [bintray repo](https://bintray.com/donovanmuller/switchbit-public/spring-cloud-dataflow-server-openshift)): https://bintray.com/donovanmuller/switchbit-public/download_file?file_path=org%2Fspringframework%2Fcloud%2Fspring-cloud-dataflow-server-openshift%2F1.1.0.RELEASE%2Fspring-cloud-dataflow-server-openshift-1.1.0.RELEASE.jar

**Comment by jakudaba** [comment]
Thank you very much, works like a charm.
