### ISSUE TITLE
Roadmap 1.2.0 Milestone

### ISSUE THREAD

**Issue by retosbb** [donovanmuller/spring-cloud-dataflow-server-openshift#16]
Hello Donovan,

I want to know how your plan looks for the integration of the SCDF 1.2.0 Release?

Regards,
Reto

**Comment by donovanmuller** [comment]
Hi @retosbb, 

https://github.com/donovanmuller/spring-cloud-deployer-openshift/commit/fe06fd4faaefc393d3e19c20d358a7f2f30b39c4 has already been updated. There are a few issues I'd like to address with the 1.2.0 release regarding builds.

Will try get to those soon!

**Comment by Chnoch** [comment]
Any updates on the timeline for the 1.2.0 release? Do you need any help for the release?

**Comment by donovanmuller** [comment]
@Chnoch The [1.2.0 release](https://github.com/donovanmuller/spring-cloud-dataflow-server-openshift/releases/tag/v1.2.0.RELEASE) is out the door!

Apologies for the delay. The day job got in the way for this release...
Any help in future would be much appreciated. Thanks.
