### ISSUE TITLE
Error in Openshift when deploying custom stream app

### ISSUE THREAD

**Issue by roberts365** [donovanmuller/spring-cloud-dataflow-server-openshift#20]
I seem to get this error when deploying my custom app to OpenShift
Can you help?

`container_linux.go:247: starting container process caused "exec: \"--spring.metrics.export.triggers.application.includes=integration**\": executable file not found in $PATH"`

Cluster is running with:
OpenShift Origins v1.4.1
donovanmuller/spring-cloud-dataflow-server-openshift:1.2.0.RELEASE
digitalwonderland/zookeeper:latest
redis:3-alpine
mysql:5.7.18
wurstmeister/kafka:0.10.2.1

Thanks

**Comment by donovanmuller** [comment]
Thanks for the feedback.

Currently traveling so difficult to try reproduce but I have a suspicion it's how the command line args are being handled. Could you please try the `boot` entry point style?

https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java#L167

**Comment by roberts365** [comment]
Thank you for getting back to me.

Do you mean using ENTRYPOINT in my Dockerfile?
If so, it is what I am currenty using.

This way,
`ENTRYPOINT java -Xms256m -Xmx1024m -Dspring.profiles.active=production -Djava.security.egd=file:/dev/./urandom -jar /usr/share/myproject/app.jar`

gives this error
`container_linux.go:247: starting container process caused "exec: \"--spring.metrics.export.triggers.application.includes=integration**\": executable file not found in $PATH"`

This way,
`ENTRYPOINT [ "sh", "-c", "java -Xms256m -Xmx1024m -Dspring.profiles.active=production -Djava.security.egd=file:/dev/./urandom -jar /usr/share/myproject/app.jar" ]`

gives this error
`--spring.metrics.export.triggers.application.includes=integration**: line 0: [: -c,: binary operator expected`

**Comment by roberts365** [comment]
Thank you for getting back to me.
I set **spring.cloud.deployer.kubernetes.entryPointStyle=boot** in my **applications.properties** file.

Setting it to **boot** and **exec** gave me this error.
`--spring.metrics.export.triggers.application.includes=integration**: line 0: [: -c,: binary operator expected`

Setting it to **shell** gave me this error.
`container_linux.go:247: starting container process caused "exec: \"--spring.metrics.export.triggers.application.includes=integration**\": executable file not found in $PATH"`

My current Dockerfile looks like this.
```
FROM docker-registry-default.ossim.io/o2/omar-base:latest
MAINTAINER DigitalGlobe-RadiantBlue
LABEL com.digitalglobe.version="" 
RUN useradd -u 1001 -r -g 0 -d $HOME -s /sbin/nologin -c "Default Application User" omar
RUN mkdir /usr/share/omar
COPY /omar-scdf-sqs-1.0.37-SNAPSHOT.jar /usr/share/omar
RUN chown -R 1001:0 /usr/share/omar
RUN chown 1001:0 /usr/share/omar
RUN chmod -R g+rw /usr/share/omar
RUN find $HOME -type d -exec chmod g+x {} +
USER 1001
WORKDIR /usr/share/omar
VOLUME /tmp
EXPOSE 8080
ENTRYPOINT java -jar /usr/share/omar/omar-scdf-sqs-1.0.37-SNAPSHOT.jar
```
Since this is not working, I am going to assume I am doing this incorrectly.
Is there an example app I can look at to see how the spring.cloud.deployer.kubernetes.entryPointStyle is being used and what the Dockerfile should look like?

Thanks again.

**Comment by donovanmuller** [comment]
I'll be back next week from travelling, I'll be able to investigate this in detail then.

What would work best, is if you could please share a sample project (preferably on GitHub, that demonstrates this issue). Then I can use that project to provide assistance...

In the meantime, I assume you've read the blog posts around this (might be a bit dates but still relevant):

1. https://blog.switchbit.io/scdf-openshift-deploying-maven-artifacts-with-custom-dockerfile/
2. https://blog.switchbit.io/spring-cloud-deployer-openshift/

**Comment by roberts365** [comment]
Here is a link to the repo https://github.com/ossimlabs/omar-scdf-sqs
Thanks again

**Comment by roberts365** [comment]
It looks like updating Openshift to version 1.5.1 fixed my issue.
Thanks for the help.
