### ISSUE TITLE
Cant deploy templates from Openshift web console

### ISSUE THREAD

**Issue by LyashenkoGS** [donovanmuller/spring-cloud-dataflow-server-openshift#22]
After successful creating templates by a bash script, I can't create pods from any of custom templates (nexus, spring-cloud-dataflow-server-openshift, spring-cloud-dataflow-server-openshift-ephemeral-datasources, etc.).  After click on the create button in a template nothing happens, it just stuck. Default templates work fine (Java -> wildfly).
minishift logs, don't show any actions also. It has been reproduced with OpenShift Master:
v1.5.1+7b451fc and v1.4.1. Credentials to the web console login: admin password: admin

**The script to run a minishift and deploy templates**

```
#!/usr/bin/env bash
#Runs minishift in virtualBox with specified RAM and CPU 

#1. clean up virtual machine and disable all addons
minishift delete
minishift addons disable admin-user
minishift addons disable anyuid
minishift addons disable xpaas
#2. enable addon to have admin cluster privileges (required to properly use some templates)
minishift addons enable admin-user
#3. deploy new one minishift with boot2docker iso, enhanced RAM and CPU number
minishift start --memory 6000  --cpus 4 --vm-driver virtualbox
#4. setup oc CLI
eval $(minishift oc-env)
#5.open an Openshift GUI in a browser
minishift console
#6.login via oc
oc login -u admin -p admin
#7. create a new project
oc new-project scdf --description="Spring Cloud Data Flow"
#8. deploy templates
curl https://raw.githubusercontent.com/donovanmuller/spring-cloud-dataflow-server-openshift/v1.1.0.RELEASE/src/etc/openshift/install-templates.sh | bash
```
But I can custom templates by executing, for example 

`oc new-app spring-cloud-dataflow-server-openshift-ephemeral-kafka`

**Comment by donovanmuller** [comment]
The getting "stuck" was an issue when OpenShift 3.4/1.4 came out if I remember correctly.

It basically came down to [this section](https://github.com/donovanmuller/spring-cloud-dataflow-server-openshift/blob/d62e9378d0a6d35a65561eed12dd577976322220/src/etc/openshift/scdf-ephemeral-datasources-template.yaml#L142-L145) in the `Service` resource definition having to be removed for the Template creation to happen as expected.

```diff
...
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: "scdf-ephemeral"
      name: "scdf-ephemeral"
      annotations:
        service.alpha.openshift.io/dependencies: '[{"name": "mysql","kind": "Service"},{"name": "redis","kind": "Service"}]'
    spec:
-      template:
-        metadata:
-          labels:
-            name: "scdf-ephemeral"
      ports:
        - name: http
          port: ${SERVER_PORT}
          targetPort: http
      selector:
        name: "scdf-ephemeral"
...
```

I'll fix this up as part of #19

**Comment by LyashenkoGS** [comment]
@donovanmuller Unfortunately, removing specified lines didn't help.

**Comment by donovanmuller** [comment]
@LyashenkoGS I have updated the Templates, please see  this https://github.com/donovanmuller/spring-cloud-dataflow-server-openshift/issues/19#issuecomment-329805850
