### ISSUE TITLE
SCDF route naming uses '.' rather than '-' as a separator

### ISSUE THREAD

**Issue by TrevorMusodza** [donovanmuller/spring-cloud-dataflow-server-openshift#26]
spring-cloud-dataflow-server-openshift creates a route with '.' instead of '-' creating a subdomain in the namespace.
Openshift uses '-' as a separator between the namespace name and the service name when naming routes created with oc expose svc [service_name], or on the web console . 
Temporary measure is to delete the route created by SCDF and recreate it with Openshift facilities. 

spring-cloud-dataflow-server-openshift example
http://service.namespace.mydomain.com

openshift default
http://service-namespace.mydomain.com

**Comment by donovanmuller** [comment]
Moved to https://github.com/donovanmuller/spring-cloud-deployer-openshift/issues/47
