### ISSUE TITLE
Jar file error

### ISSUE THREAD

**Issue by roberts365** [donovanmuller/spring-cloud-dataflow-server-openshift#30]
Hello,
I am getting the following error when trying to deploy spring-cloud-dataflow-server-openshift:1.2.1.RELEASE in minishift.

> Error: Unable to access jarfile /maven/spring-cloud-dataflow-server-openshift.jar

Is there something I need to set?

**Comment by donovanmuller** [comment]
Hi @roberts365,

Thanks for reaching out.
Could you please let me know which step you're failing on? I.e. are you using the [Templates](https://donovanmuller.github.io/spring-cloud-dataflow-server-openshift/docs/1.2.1.RELEASE/reference/htmlsingle/#_installing_the_data_flow_server) to install?

**Comment by roberts365** [comment]
Yes.  I am using scdf-ephemeral-datasources-rabbitmq-template.yaml to install.
Everything comes up except the spring close dataflow server.

**Comment by roberts365** [comment]
Thank you
