### ISSUE TITLE
Do you have any plan to support OpenShift 4.x

### ISSUE THREAD

**Issue by gogangipark** [donovanmuller/spring-cloud-dataflow-server-openshift#36]
In My project, I have tried to use spring cloud data flow at OpenShift 4.X.

This project support openshift 3.x until now.

I hope that It will support OpenShift 4.x.

thank you.

**Comment by donovanmuller** [comment]
Hi @gogangipark, please see https://github.com/donovanmuller/spring-cloud-dataflow-server-openshift/issues/33#issuecomment-451510279
